services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: infog2-web:latest
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lu_estilo
      - SECRET_KEY=your-secret-key-here
      - ALGORITHM=HS256
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13.12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lu_estilo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
